server:
  port: 3001
spring:  application:    name: zuul
  rabbitmq:
    host: 192.168.64.5
    port: 5672
    username: admin
    password: admin 
eureka:  client:    service-url:      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
  
    
zuul:
  retryable: true
  routes:
    item-service: "/item-service/**"
    user-service: "/user-service/**"
    order-service: "/order-service/**"
management:  endpoints:    web:      exposure:        include: hystrix.stream